name: "Run Splunk App Inspect Check"
description: "Run Splunk app-inspect check, cloud-inspect check and ssai (self-service) check on the App build to make sure App will pass the checks on Splunkbase."
inputs:
  app_build:
    description: "Splunk App Build"
    required: true
  splunkbase_username:
    description: "Username required to call the Splunkbase API for App-Inspect"
    required: true
  splunkbase_password:
    description: "Password required to call the Splunkbase API for App-Inspect"
    required: true
  report_prefix:
    description: "Report prefix. Default is app. It will generate app_app_inspect_check.html, app_cloud_inspect_check.html, app_ssai_inspect_check.html files."
    required: false
    default: "app"
outputs:
  stdout:
    description: "Program stdout"
  stderr:
    description: "Program stderr"
  error:
    description: "A string of 'true' or 'false' that tells if there were errors."
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "purple"
  icon: "play"